version: '3.4'

services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  postcomments.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  post.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
