version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: apigateway
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Bff/Web.Bff.ApiGateway/Dockerfile
    environment:
    - RabbitMQ=rabbitmq
    - QuestionsGrpc=http://question.api:6002 
    ports:
    - "5000:80" 

  identity.api:
    image: ${DOCKER_REGISTRY-}identity.api
    container_name: identity.api
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    environment:
    - ConnectionString=Server=sqldata;Database=IdentityDb;User Id=admin;Password=Qwerty123
    - RabbitMQ=rabbitmq
    - Cache=cachedata
    ports:
    - "5001:80"  

  question.api:
    image: ${DOCKER_REGISTRY-}question.api
    container_name: question.api
    build:
      context: .
      dockerfile: src/Services/Question/Question.API/Dockerfile
    environment:
    - ConnectionString=Server=sqldata;Database=QuestionDb;User Id=admin;Password=Qwerty123
    - RabbitMQ=rabbitmq
    - Cache=cachedata
    ports:
    - "5002:80"  
    - "6002:81"

  answer.api:
    image: ${DOCKER_REGISTRY-}answer.api
    container_name: answer.api
    build:
      context: .
      dockerfile: src/Services/Answer/Answer.API/Dockerfile
    environment:
    - ConnectionString=Server=sqldata;Database=AnswerDb;User Id=admin;Password=Qwerty123
    - RabbitMQ=rabbitmq
    - Cache=cachedata
    ports:
    - "5003:80" 

  quest.api:
    image: ${DOCKER_REGISTRY-}quest.api
    container_name: quest.api
    build:
      context: .
      dockerfile: src/Services/Quest/Quest.API/Dockerfile
    environment:
    - ConnectionString=Server=sqldata;Database=QuestDb;User Id=admin;Password=Qwerty123
    - RabbitMQ=rabbitmq
    - Cache=cachedata
    ports:
    - "5004:80" 

  quest.backgroundtasks:
    image: ${DOCKER_REGISTRY-}questbackgroundtasks
    container_name: quest.backgroundtasks
    build:
      context: .
      dockerfile: src/Services/Quest/Quests.BackgroundTasks/Dockerfile
    environment:
    - RabbitMQ=rabbitmq

  test.api:
    image: ${DOCKER_REGISTRY-}test.api
    container_name: test.api
    build:
      context: .
      dockerfile: src/Services/Test/Test.API/Dockerfile
    environment:
    - ConnectionString=Server=sqldata;Database=TestDb;User Id=admin;Password=Qwerty123
    - RabbitMQ=rabbitmq
    - Cache=cachedata
    ports:
    - "5005:80" 

  theme.api:
    image: ${DOCKER_REGISTRY-}theme.api
    container_name: theme.api
    build:
      context: .
      dockerfile: src/Services/Theme/Theme.API/Dockerfile
    environment:
    - ConnectionString=Server=sqldata;Database=ThemeDb;User Id=admin;Password=Qwerty123
    - RabbitMQ=rabbitmq
    - Cache=cachedata
    ports:
    - "5006:80" 

  membership.api:
    image: ${DOCKER_REGISTRY-}membership.api
    container_name: membership.api
    build:
      context: .
      dockerfile: src/Services/Membership/Membership.API/Dockerfile
    environment:
    - ConnectionString=Server=sqldata;Database=MembershipDb;User Id=admin;Password=Qwerty123
    - RabbitMQ=rabbitmq
    - Cache=cachedata
    ports:
    - "5007:80" 

  membership.backgroundtasks:
    image: ${DOCKER_REGISTRY-}membershipbackgroundtasks
    container_name: membership.backgroundtasks
    build:
      context: .
      dockerfile: src/Services/Membership/Membership.BackgroundTasks/Dockerfile
    environment:
    - RabbitMQ=rabbitmq

  point.api:
    image: ${DOCKER_REGISTRY-}point.api
    container_name: point.api
    build:
      context: .
      dockerfile: src/Services/Point/Point.API/Dockerfile
    environment:
    - ConnectionString=Server=sqldata;Database=PointDb;User Id=admin;Password=Qwerty123
    - RabbitMQ=rabbitmq
    - Cache=cachedata
    ports:
    - "5008:80" 

  sqldata:
    image: postgres:13.3
    container_name: sqldata
    environment:
       POSTGRES_USER: "admin"
       POSTGRES_PASSWORD: "Qwerty123"
    volumes:
      - corviana-backend-sqldata:/var/lib/postgresql/data

  cachedata:
    container_name: cachedata
    image: redis:latest
 
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
    corviana-backend-sqldata:
        driver: local














